version: '3.3'
volumes:
  data:
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  scrapper:
    build:
      dockerfile: scrapper/Dockerfile
    environment:
      SCHEDULE: 11:00
      CITY: SAO PAULO
      DB_CONNECTION_STRING: postgres://postgres:postgrespw@postgres:5432
      SERVICE: weather.com
      POSTGRES_PASSWORD: postgrespw
    depends_on:
      - postgres
  monitor:
    build:
      dockerfile: monitor/Dockerfile
    environment:
      SCHEDULE: 10:00
      SENDER_EMAIL: weather.monitor@outlook.com
      EMAIL_PASSWORD: weather.M0N1T0R
      RECEIVER_EMAIL: decarv.henrique@gmail.com
      SMTP_SERVER: smtp-mail.outlook.com
      SMTP_SERVER_PORT: 587
      DB_CONNECTION_STRING: postgres://postgres:postgrespw@postgres:5432
      POSTGRES_PASSWORD: postgrespw
      TEMPERATURE_MIN: 10
      TEMPERATURE_MAX: 20
      PRECIPITATION_PROBABILITY_MIN: 50
    depends_on:
      - postgres
